import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../app/ui/styles/globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body className={`${inter.className} w-screen h-screen`}>{children}</body>
    </html>
  );
}
